development:
  adapter: postgresql
  encoding: unicode
  database: uif2012
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5


production:
  adapter:	postgresql
  encoding:	unicode
  pool:	5
  database: uif2012
  username: urban_impact
  password: edglover
  host: localhost
  # database: d88d5mttp1l4s
  # username: mjqepduomupsce
  # password: gBGEZ6Cf7r-2BlGlhsjTziQvrs
  # host: ec2-54-243-223-183.compute-1.amazonaws.com
  port:	5432

